apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: k8sdotnetapp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: k8sdotnetapp
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=appdb;Username=appuser;Password=apppass123"
