apiVersion: v1
kind: Service
metadata:
  name: dotnetapi
  namespace: k8sdotnetapp
spec:
  selector:
    app: dotnetapi
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP