apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: k8sdotnetapp
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Api__BaseUrl: "http://dotnetapi"