apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: k8sdotnetapp
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80 # servicenin cluster ici erisildiginde kullanacagi port
      targetPort: 8080 #container icindeki port yani kestrel sunucusunun dinledigii port
  type: ClusterIP