apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8sdotnetapp-ingress
  namespace: k8sdotnetapp
spec:
  rules:
    - host: k8sdotnetapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.k8sdotnetapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dotnetapi
                port:
                  number: 80
